### PR TITLE
fix #48

### LINKED ISSUE #48: NoSuchElementException: None.get
```
[info]   java.util.NoSuchElementException: None.get
[info]   at scala.None$.get(Option.scala:349)
[info]   at scala.None$.get(Option.scala:347)
[info]   at com.danielasfregola.randomdatagenerator.RandomDataGenerator.random(RandomDataGenerator.scala:17)

```

### PR DESCRIPTION
**Pull request by pawelkaczor**

### CODE REVIEW

File: src/main/scala/com/danielasfregola/randomdatagenerator/RandomDataGenerator.scala [hunk 1]
```diff
@@ -2,19 +2,26 @@ package com.danielasfregola.randomdatagenerator
...
 
   def random[T](implicit arb: Arbitrary[T]): T = random(1)(arb).head
 
-  def random[T](n: Int)(implicit arb: Arbitrary[T]): Seq[T] = {
+  @tailrec
+  final def random[T](n: Int)(implicit arb: Arbitrary[T]): Seq[T] = {
     val gen = Gen.listOfN(n, arb.arbitrary)
     val optSeqT = gen.apply(Gen.Parameters.default, seed)
-    optSeqT.get
+    optSeqT match {
```
Comment (DanielaSfregola) [inline src/main/scala/com/danielasfregola/randomdatagenerator/RandomDataGenerator.scala:21]: I like this! Definitely safer than using `.get`

**Review by DanielaSfregola — APPROVED** [review]
Hi @pawelkaczor,

thank you very much for this contribution and for raising (and fixing) this bug!
